# Generated by Django 3.2.5 on 2022-05-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='miles',
            field=models.IntegerField(),
        ),
    ]
